<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\AccountController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "api" middleware group. Make something great!
|
*/

// Debug/Health check route (temporary)
Route::get('/debug/health', function () {
    try {
        // Test database connection
        \DB::connection()->getPdo();
        $dbStatus = 'OK';

        // Test cache
        \Cache::put('test', 'value', 10);
        $cacheStatus = \Cache::get('test') === 'value' ? 'OK' : 'FAILED';

        // Test OrangeMoney service
        $omService = app(\App\Services\OrangeMoneyService::class);
        $testUser = $omService->checkUser('221771234567');
        $omStatus = $testUser ? 'OK' : 'FAILED';

        return response()->json([
            'status' => 'OK',
            'timestamp' => now(),
            'checks' => [
                'database' => $dbStatus,
                'cache' => $cacheStatus,
                'orange_money' => $omStatus,
                'environment' => app()->environment(),
                'debug_mode' => config('app.debug'),
            ],
            'server_info' => [
                'php_version' => PHP_VERSION,
                'laravel_version' => app()->version(),
            ]
        ]);
    } catch (\Exception $e) {
        return response()->json([
            'status' => 'ERROR',
            'error' => $e->getMessage(),
            'file' => $e->getFile(),
            'line' => $e->getLine(),
            'trace' => config('app.debug') ? $e->getTraceAsString() : null
        ], 500);
    }
});

// Authentication routes (public)
Route::post('/auth/initiate-login', [AuthController::class, 'initiateLogin']);
Route::post('/auth/complete-login', [AuthController::class, 'completeLogin']);

// Protected routes (require authentication)
Route::middleware(['auth:api'])->group(function () {
    // Authentication
    Route::get('/auth/user', [AuthController::class, 'getUser']);
    Route::post('/auth/refresh-token', [AuthController::class, 'refreshToken']);
    Route::post('/auth/logout', [AuthController::class, 'logout']);

    // Transactions
    Route::post('/transactions', [TransactionController::class, 'createTransaction']);
    Route::get('/transactions', [TransactionController::class, 'listTransactions']);
    Route::delete('/transactions/{id}', [TransactionController::class, 'cancelTransaction']);

    // Accounts
    Route::get('/accounts/details', [AccountController::class, 'getAccountDetails']);
    Route::post('/accounts/create', [AccountController::class, 'createAccount']);
    Route::delete('/accounts/{id}', [AccountController::class, 'deleteAccount']);
});

// API Documentation routes (public) - Auto-generated by L5-Swagger
Route::get('/docs', function () {
    return view('swagger.index');
})->name('api.docs');

// L5-Swagger will auto-generate the JSON documentation from controller annotations
